uniqush/uniqush-push

srv/apns.go

@monnand We ran into this case running uniqush-push at scale and hit an error here -- it seems conn should always be nil if err is not nil.

Don't close conn when it will be nil

---

srv/apns.go

When this routine terminates without closing resChan, the go routine reading from resChan gets stuck expecting more input.

Fix a memory leak

---

Dockerfile
scripts/run-dockerfile.sh

@monnand Saw someone on the mailing list asking for a Dockerfile. Made a really basic one with a run script. It will currently just "go get" uniqush-push but will use the conf/uniqush-push.conf from the working directory, so the user can set the redis db host/port appropriately and such.
I would just use the Redis Dockerfile from dockerhub as I have in the past for playing with this with Docker personally.
In the future maybe it should actually build what's in the current working directory but it gets the ball rolling.

Add basic Dockerfile and run script for it

---

pushbackend.go

@monnand A colleague figured out this one. We were having issues with the "/stop" API not working when the service is under load on production -- it would only work once I drained enough traffic away.

Call Finalize() on PushServiceManager if Finalize() is called on PushBackEnd

---

srv/adm.go
srv/c2dm.go

Thanks to Tyson Andre for this:
There is a race condition where the loop variable `dp` being iterated
over may be changed before the corresponding goroutine may execute.
We don't use amazon notifications or Google's c2dm(we use gcm instead), so this won't fix any of our concurrency problems.
This was introduced years ago in the upstream code, in 97a19790 and b11f9a19
This type of race condition is mentioned in
https://golang.org/doc/effective_go.html#channels
Detected with the command:
`go tool vet --all=true .`

Fix concurrency issues in adm & c2dm discovered by "go vet"

---

srv/apns.go

@monnand 
"Channel resChan passed to function resultCollector() is actually self.resultChan, see line 448. Closing this channel will affect other goroutines reading from/writing to this channel since it is shared between goroutines. I checked the code again, I think the memory leak bug is actually caused by un-closed req.resChan. If I'm correct, then it means you will have lots of goroutines waiting in function waitResults() because the channel resChan passed to this function is never closed."
Revert "Merge pull request #60 from or-else/patch-1"
This reverts commit 3d726e38ccdb782e1aed2991cb09a595c5242898, reversing
changes made to 1948046c27947d1a48185019b58630d878cd51b1.

Fix issue #68 per monnand

---

push/errors.go
pushbackend.go
srv/gcm.go

@monnand There's nothing we can really do with an InvalidRegistration but drop it from the DB and log it. We had a bunch of these I believe from a botched batch import of device registrations

Drop GCM "InvalidRegistration" delivery points from database

---

configparser.go

As of January 25th, code.google.com no longer serves git.
- http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html
Created a mirror ifwe/goconf on github with no plans to modify it.
Feel free to export https://code.google.com/archive/p/goconf/ to the uniqush
project later.

code.google.com/p/goconf no longer works. Use a github fork instead.

---

db/pushdb.go
db/pushdb_test.go
db/pushredisdb.go

Previously, if there were redis errors, they would not tell you what
operation caused the error (e.g. errors were similar to "Redis error:
Missing key").
Add details on context of the errors, both at the redis level and at the
db abstraction level.
Additionally, stop using `import .`, and use full module name instead
when using other modules.
This is discouraged: https://golang.org/doc/effective_go.html#package-names
> (Don't use the import . notation, which can simplify tests that must
> run outside the package they are testing, but should otherwise be
> avoided.)

Add more detail to the redis db errors; show how and where they happened

---

main.go
pushbackend.go
restapi.go
restapi_pushresponse.go
restapi_response.go
restapi_simpleresponse.go
srv/apns-test/apns-test.sh

By using a JSON response format, this allows uniqush clients to know if the API was successful.
API clients will be able to easily determine the reason an API failed, without resorting to heuristics (checking if the response contains a certain string).
Additionally, it is much easier for clients to process the outcome of a push, when a push involves more than one device.
- bump version from 1.5.x to 1.6.0, since the API response format changed. No change in functionality or api request format. **(or should this be a major version change, instead?)**
(This is mostly the same as what we use internally. 
The original author's commits were edited to remove a field that wasn't used by upstream. 
Additionally, `go fmt` was run on every commit, and some commits were squashed)
Barely related to …

Change the response format from logger output to a structured JSON response

---

push/errors.go
push/pushservicemngr.go
push/pushservicetype.go
pushbackend.go
restapi.go
restapi_response.go
srv/adm.go
srv/apns.go
srv/gcm.go

Include errorMsg in uniqush responses; create common interface PushError
errorMsg in API responses makes it slightly easier to debug problems in the clients of uniqush
without referring to log files.
Also, add additional context for some errors, etc.
Add a specific interface indicating which errors will be passed to the push backend.
Modules now use `PushError` for public APIs, and other `error` subtypes,
such as `net.Error`, `error`, etc., for implementation detail.
- This makes it easier to refactor code. If you know something isn't a
`PushError`, it's clearer that it may need to be handled specially.
(E.g. a `net.Error` may influence the retry behavior of the APNS module.
Where you see `err PushError`, you know it definitely isn't a `net.Error`)
- Add `ErrorReport`, which does the same …

 Include errorMsg in uniqush responses; create common interface PushError

---

srv/apns.go
srv/apns/common/json.go
srv/apns/common/json_test.go

(Where reasonable)
According to apple support (Can be seen if you attempt to send a notification)
> "APNs does not support the JSON \U notation; just put the UTF-8 character in
> the alert directly, such as ∃ instead of \U2203."
International characters are already unescaped. However, uniqush should
manually unescape '<', '>', '&', and '"', in case they occur in a push
notification payload.
(The push notification message would render '"' as "\u0022" otherwise)
Continuing to escape the subset of obscure ascii escape codes from 0-31.
(In a later PR, may want to test passing them along in a format that apps can decode)
See issue 8592 from https://github.com/golang/go/issues/ : "encoding/json: No way to avoid HTMLEscape when Marshal()-ing"

Fix json encoding of apns payloads - remove unsupported \u notation.

---

push/errors.go

in Error(), fmt.Sprintf was calling Error(), of the same object.
fmt.Sprintf should be passed the member err.Err instead.
Fix bug introduced in b11f9a19 or earlier

Fix stack overflow in errors.go

---

restapi_response.go

If they weren't set/were empty, they don't need to be returned
- e.g. ErrorMsg isn't useful on success
- e.g. PushServiceProvider may not be applicable, a push error may be caused by the request data instead

Omit empty values from the JSON being returned from the REST API

---

conf/uniqush-push.conf
configparser.go
db/pushdb.go
db/pushredisdb.go
db/rawdb.go
main.go
push/pushpeer.go
pushbackend.go
restapi.go
srv/apns/apns-test/apns-test.sh

/subscriptions shows the subscription details (tokens/regids, push
service type, service names) of a given subscriber. If no service is
provided in the query, all services are queried.
As part of this change, the set of all service names must be tracked in
redis. KEYS would be too slow to use, so a new set SERVICES.{0} was added.
- If the redis databases sharded, then the {0} could be used as a shard scheme,
to avoid hitting multiple databases for what would be a small set.
- /rebuildserviceset is added, to be manually run to create the service
set for pre-existing uniqush users. This hasn't been fully tested yet.
For convenience, /psps was also added.
- The API response maps service names to a list of psps with that service name.
(From the documentation, I'm not sure if it is meant to be …

Commit /subscriptions, /services and /rebuildserviceset API endpoints

---

push/pushservicemngr.go

To make singleton creation a more secure one using sync.Once.

Use sync.Once as singleton implimentation

---

srv/adm.go
srv/adm_test.go
srv/apns/payload.go
srv/apns/push_service_test.go
srv/gcm.go
srv/gcm_test.go

through "uniqush.payload.apns", "uniqush.payload.gcm", and "uniqush.payload.apns", respectively.
1. If those parameters exist, start using them **instead** of the existing method for building the (inner) data of the payload. This allows clients more flexibility to add custom data (E.g. nested objects in APNS payloads).
The new version of the code should behave the same way as the old method if none of the POST data begins with "uniqush." (This PR rearranged the existing code and renamed some variables)
2. Add test cases for both methods of building payloads.
3. Start removing unrecognized POST fields beginning with "uniqush." from the payloads. E.g. don't accidentally include "uniqush.payload.gcm" in the inner body of an APNS payload.
4. Fix a bug in "content-available" for APNS. This …

Allow passing raw payloads to the APNS, GCM, and ADM modules

---

pushbackend.go
restapi_response.go

Add a new boolean indicator “modifiedDp” to “successDetails” in case
the DeliveryPoint was modified (in case on canonical ID).
Example:
{"type":"Push","date":1461863706,"successCount":1,"failureCount":0,"drop
pedCount":0,"successDetails":[{"requestId":"5722451a-p2SvjxrnRGLTEYQ4U7m
INg==","service":"ps001","from":"10.0.0.102:55851","subscriber”:”xxx”,”p
ushServiceProvider":"gcm:yyy”,”deliveryPoint":"gcm:zzz”,”messageId":"gcm
:iii”,”code":"UNIQUSH_SUCCESS","modifiedDp":true}],"failureDetails":[],"
droppedDetails":[]}

Indicate that the  DeliveryPoint was modified #113

---

srv/gcm.go
srv/gcm_push_service_test.go

instead of creating a lingering connection for every push.
Doing this greatly reduces the number of open connections for GCM, and the number of connections. It also decreases CPU usage noticeably when there are active GCM PSPs, and should decrease latency.
Previously, uniqush-push was creating http.Clients every time a push request was made. Each http.Client has its own instance of a connection pool.
https://golang.org/pkg/net/http/#pkg-overview
>  Clients and Transports are safe for concurrent use by multiple goroutines and for efficiency should only be created once and re-used.
Add a timeout of 10 seconds for pushes to GCM servers. It's undesirable to wait forever for a request to finish if there are network errors.

Use a single shared connection pool for GCM pushes, set timeouts on gcm requests

---

configparser.go
push/pushpeer_test.go
push/pushservicemngr.go
push/pushservicetype.go
pushbackend.go
restapi.go
restapi_response.go
srv/adm.go
srv/apns/binary_api/processor_test.go
srv/apns/push_service.go
srv/apns/push_service_test.go
srv/gcm.go
srv/gcm_push_service_test.go

`/previewpush` accepts the same payload query params as `push`.
However, it does not accept subscribers or services.
Instead, it requires the pushservicetype param (apns, gcm, or adm)
Being able to see what Uniqush is sending is useful for
debugging iOS,Android,etc. client issues handling/parsing notifications.
(Note: Fields such as TTL are outside of the JSON payload for APNS)
Subscriber data, if part of the "payload", is replaced with dummy
subscriber data in the returned result.
Add tests, update mocks to implement Preview.
Use reflect.DeepEqual for a unit test - The order of keys is not
guaranteed.

Add /previewpush endpoint to preview payloads sent to push services.

---

db/pushdb_test.go

Fixes #143
goredis v6 is also out, but would want to support dependency versioning first

use redis.v5 in main code and unit tests (Bumped from redis.v3)

---

main.go
srv/cloud_messaging/cloud_messaging.go
srv/cm_mocks.go
srv/fcm.go
srv/fcm_push_service_test.go
srv/fcm_test.go
srv/gcm.go
srv/gcm_push_service_test.go
srv/gcm_test.go

Based on PR #139 
This uses anonymous field (in a manner similar to subclassing, but very different) to factor out code common to GCM and FCM http://dennissuratna.com/using-anonymous-field-to-extend-in-go/
- had duplicated code, which would double the work on future changes to GCM/FCM modules and possibly lead to inconsistencies/bugs.
- I recently set up android studio with the FCM mode from https://firebase.google.com/docs/cloud-messaging/android/first-message , and I'm working through the tutorial.
This will be tested with android devices, GCM on iOS/other may or may not need more work
Still need to manually call /addpsp, /push, and /subscribe on a local instance of uniqush to test this manually
- Projects used to test this:
https://firebase.google.com/docs/cloud-messaging/android/first- …

FCM support (refactored)

---

main.go

This includes bumping APNS binary protocol version from 1 to 2
(invisible to clients),
and initial FCM support (pushservicetype=fcm), refactoring GCM to share code with FCM.

Bump version id returned by uniqush /version endpoint

---

srv/cloud_messaging/cloud_messaging.go
srv/fcm.go
srv/fcm_test.go
srv/gcm.go
srv/gcm_test.go

The Name() was included in srv/cloud_messaging/,
having each service override it is confusing and redundant.

Remove redundant Name() implementation, convert initialism -> acronym

---

.travis.yml

Benefits: faster Travis CI runs, more up to date libraries.
(Not very important since golang produces static binaries)

Update the travis CI version

---

.travis.yml
push/pushpeer.go
srv/cloud_messaging/cloud_messaging.go
srv/fcm_push_service_test.go
srv/gcm_push_service_test.go
srv/gcm_test.go
util/json.go
util/json_test.go

otherwise, "<" is needlessly escaped
(Not intended to ever render this as HTML)
Unescaped JSON reduces the size of GCM payloads,
and prevents the size from increasing when providing raw gcm/fcm payloads.
Analyze format strings of expressions such as log.Configf from
uniqush-log
Use race condition checker when running travis CI tests.

Use unescaped JSON for payloads. Stricten CI checks.

---

main.go

+ New feature: Add /previewpush endpoint to preview the payload that would be
generated and sent to push services. (Issue #140)
This helps with debugging.
+ Maintenance: Update APNS binary provider API(default) from version 1 to version 2.
+ Maintenance: Upgrade to redis.v5 (Issue #143)
+ New provider: Add FCM support. (Issue #148)
The parameters that would be provided to /addpsp, /subscribe, and /push are
the same as they would be for GCM. (Replace "fcm" with "gcm")
+ New feature: Add support APNS HTTP2 API (Issue #157, PR #173)
This gives more accurate results on whether a push succeeded,
and should not impact Uniqush's performance.
To set this up, call /addpsp (to create a new provider or modify an
existing provider) with the same params you would use to create a new
APNS endpoint for …

Update the release version to 2.3.0, skipping 2.2.1

---

.travis.yml
srv/cloud_messaging/cloud_messaging.go
srv/fcm.go
srv/fcm_test.go
srv/gcm.go
srv/gcm_push_service_test.go
srv/gcm_test.go

To start with, do the simplest possible thing and
allow users to provide these as a JSON blob over the REST API.
- E.g. the following (clients should obviously URL encode the values)
uniqush.payload.fcm={"title":"MyTitle","body":"NotifBodyText"}
See the following links
- https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages
-https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages
"notification" payloads are rendered directly on the device by GCM,
without needing the client apps to do anything (similar to APNS).
On a tangent, APNS now has silent notifications, and uniqush doesn't
support those yet.
Example
-------
Start a server
```
$ ./uniqush-push -config conf/uniqush-push.conf
[WebFrontend][Config] …
```

For #177 : Support GCM&FCM "notification" payloads.

---

main.go

New features:
- Initial support for GCM/FCM "notification" pushes (Documented in PR #185).
`uniqush.notification.gcm` and `uniqush.notification.fcm` can be used
as fields for `/push`, with the JSON blob to send GCM/FCM for the
optional "notification" message.
"notification" messages will let GCM/FCM display the notification for you.
Maintenance:
- Change from https://android.googleapis.com/gcm/send to
https://gcm-http.googleapis.com/gcm/send
- Bump go version used to compile releases
Bug fixes:
- Improve logging subscriber name in failed API requests.

Update uniqush's version to 2.4.0

---

configparser.go

The contents are identical. ifwe/goconf isn't used elsewhere.
Closes #183

Move goconf dependency to uniqush github project

---

srv/apns/payload.go

iOS supports title-loc-key and title-loc-args since iOS 8.2.
This PR adds support for the 2 new keys.
See https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

Support title-loc-key and title-loc-args

---

srv/apns/payload.go

Currently, you can't add empty strings to the loc-args array. What bothers me is that it just silently ignores the empty string, which could possibly break template implementations as a arg on index 4 would suddenly be on index 3.

Allow empty strings in APNS loc-args and title-loc-args ("loc-args=,arg1" is now treated as 2 args)

---

.gitignore
srv/apns/binary_api/processor.go
srv/apns/payload.go
srv/apns/push_service.go
srv/apns/push_service_test.go

Get rid of a leftover check that was accidentally limiting
some APNS HTTP2 payloads to 2KB.
The check is needed in only one place; that place is
srv/apns/push_service.go
This check is duplicated in srv/apns/http_api/processor.go and
srv/apns/binary_api/processor.go
When uniqush.apns_voip=1 is passed to /push alongside uniqush.http2=1,
limit the payload size
For #202

Fix bug in checks of payload size, add uniqush.apns_voip=1 option.

---

main.go

- Support "title", "title-loc-key", and "title-loc-args"
- Support larger APNS payloads.
Support 5120 byte payloads for APNS voip pushes
(Where the Cert is a VOIP cert and `uniqush.apns_voip=1` is part of
the query params in the call to /push
- Support more granular loglevel levels in uniqush config files:
alert, error, warn/warning, standard/verbose/info, and debug

Release uniqush-push 2.5.0

---

main.go
srv/gcm.go

This has been tested with a prod and testing version
of an application using `uniqush-push`.
This will not have any impact on how uniqush represents
or updates the subscriber database for a GCM application.
(Future PRs may or may not update GCM subscriptions, e.g. on an as-needed basis or if a migration is started)
No issues were found. Pushes went through,
and the subscription did not have any unexpected behavior
(e.g. did not get unregistered as a side effect)
This will be necessary when GCM servers are decommissioned on April 2019.

Change the GCM endpoint to FCM (For Issue #210)

---

NEWS.md
main.go

Most of the changes are fixes for linter warnings or notices.
Notable changes:
- Bugfix: Fix the rare "No device" errors seen when retrying a push.
(PR #222)
- Bugfix: Fix the regular expression used as a sanity check of
subscriptions and services. (PR #222)
The intended accepted characters for use in services and
subscriptions were `a-z, A-Z, 0-9, -, _, @ or .`
Forbid using the backtick in service and subscription names
(this was accidentally permitted by the invalid regex).
Continue allowing a small number other invalid characters for now,
those may be deprecated in future releases.

Release uniqush-push 2.6.1.
